#-------------DYNAMODB------------------------------------ 
workersTableName: Workers
workersSeeder: [./seeds/workers.json]
workersTableGSI: WorkersRekognitionIdIndex

registersTableName: Registers
registersSeeder: [./seeds/registers.json]

#-------------REKOGNITION------------------------------------ 
workersRekognitionCollection: workers

#-------------S3------------------------------------ 
workersImagesBucketName: workersimagesbucket

#-------------API GATEWAY------------------------------------ 
apiUrls:
  admins: admins
  workers: workers

