#-------------DYNAMODB------------------------------------ 
workersTableName: Workers
workersSeeder: [./seeds/workers.json]
workersTableGSI: WorkersRekognitionIdIndex

registersTableName: Registers
registersSeeder: [./seeds/registers.json]

#-------------REKOGNITION------------------------------------ 
workersRekognitionCollection: workers

#-------------S3------------------------------------ 
workersImagesBucketName: workersimagesbucket

#-------------API GATEWAY------------------------------------ 
apiUrls:
  admins: admins
  workers: workers

#---------------COGNITO---------------
cognitoARN: arn:aws:cognito-idp:us-east-1:617503621622:userpool/us-east-1_ET2XCCtKe

